# Setup
title: Cognimates
email: cognimates@gmail.com
description: >-
 cognimates 
baseurl: "/"
url: "http://cognimates.me"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-redirect-from
include: ['_pages']

# Assets
sass:
  style: :compressed

redirects: yes
